# .travis.yml
# ...
script:
  - npm run build -- -prod # build app and prepare dist folder
# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true
