# .travis.yml
# ...
before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

install:
  - npm install
script:
  - npm run build -- -prod # build app and prepare dist folder
# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
  local-dir: dist
  verbose: true
